### ISSUE TITLE
partitions_to_exactly_c expects collection to be type set

### ISSUE THREAD

**Issue by ifryed** [erelsgl/fairpy#11]
The function 'partitions_to_exactly_c' in partitions.py inside the 'indivisible' package expects to receive a set for **collections** and passes it on to 'partitions_to_at_most_c' which expects to receive a list,and in fact dose not work with a set.

**Comment by erelsgl** [comment]
Fixed here https://github.com/erelsgl/fairpy/commit/1167e658c9e9ea465f81ac9beca9441700b393f4
